### ISSUE TITLE
Image Magick not found!

### ISSUE THREAD

**Issue by jimmysh2** [christiansiegel/video-qr-code-scanner#1]
while installing zbar it requires image magick.
but i installed it without image magick then finally i get the following error:

VIDEOIO ERROR: V4L2: Pixel format of incoming image is unsupported by OpenCV
Unable to stop the stream: Device or resource busy

Can you please help?

**Comment by christiansiegel** [comment]
Looks like some compatibility issue with your camera and OpenCV. I'm not an expert in that matter, but if you google the error message you'll find a bunch of discussions on how to possibly debug and solve it. Have you tried any of those?

**Comment by jimmysh2** [comment]
I installed zbar "application" for detecting and decoding qr codes.
Thank you for your response.
